language: php

matrix:
  include:
    - php: 7.2
      dist: bionic
      env: COMPOSER_OPTS=""
    - php: 7.3
      dist: bionic
      env: COMPOSER_OPTS=""
    - php: 7.4
      dist: bionic
      env: COMPOSER_OPTS=""
    - php: nightly
      dist: bionic
      env: COMPOSER_OPTS="--ignore-platform-reqs"
  allow_failures:
    - php: nightly
      env: COMPOSER_OPTS="--ignore-platform-reqs"

cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer install $COMPOSER_OPTS

script:
  - vendor/bin/grumphp run
  - composer test
  - composer infection
  - composer psalm

after_success: bash <(curl -s https://codecov.io/bash)
