language: php

php:
  - "7.2"
  - "7.3"
  - "7.4"
#  - "nightly"

#allow_failures:
#  - "nightly"

cache:
  directories:
    - $HOME/.composer/cache

script:
  - composer install --ignore-platform-reqs
  - vendor/bin/grumphp run
  - composer test
  - composer infection
  - composer psalm

after_success: bash <(curl -s https://codecov.io/bash)
